const mainMenu = [
  {
    id:'cold-apetizers',
    image:'img/meat.jpg',
    groupName: 'Холодные закуски',
    dishes:[
      {
        name:'Мясные яства из деликатесов собственного приготовления',
        unit: 'гр',
        weight: 170,
        price: 420,
      },
      {
        name: 'Рыбная тарелка к застолью',
        unit: 'гр',
        weight: 170,
        price: 460,
      },
      {
        name: 'Ассорти сыров',
        unit: 'гр',
        weight: 150,
        price: 360,
      },
      {
        name: 'Блюдо из свежих овощей',
        unit: 'гр',
        weight: 180,
        price: 260,
      },
      {
        name: 'Соленья домашние',
        unit: 'гр',
        weight: 200,
        price: 260,
      },
      {
        name: 'Грибочки из бочки с луком и сметаной',
        unit: 'гр',
        weight: 180,
        price: 350,
      },
      {
        name: 'Филе сельди с молодым картофелем',
        unit: 'гр',
        weight: 200,
        price: 240,
      },
      {
        name: 'Холодец домашний из трех видов мяса',
        unit: 'гр',
        weight: 230,
        price: 260,
      },
      {
        name: 'Блинные рулетики с семгой и красной икрой',
        unit: 'гр',
        weight: 100,
        price: 350,
      },
      {
        name: 'Рулетики из языка с творожным сыром и хреном',
        unit: 'гр',
        weight: 200,
        price: 350,
      },
      {
        name: 'Семужка собственного посола со сливочным сыром',
        unit: 'гр',
        weight: 170,
        price: 380,
      },
      {
        name: 'Ростбиф из говяжьей вырезки с соусом из свежих трав',
        unit: 'гр',
        weight: 180,
        price: 580,
      },
      {
        name: 'Маслины, оливки',
        unit: 'гр',
        weight: 50,
        price: 120,
      },
      {
        name: 'Лимоны',
        unit: 'гр',
        weight: 100,
        price: 100,
      },
    ],
  },
  {
    id: 'salads',
    image:'img/salads.jpg',
    groupName: 'Салаты',
    dishes: [
      {
        name: 'Салат с ростбифом и свежими овощами',
        unit: 'гр',
        weight: 200,
        price: 450,
      },
      {
        name: 'Салат со слабосоленым лососем, картофелем и свежим огурцом',
        unit: 'гр',
        weight: 200,
        price: 430,
      },
      {
        name: 'Цезарь с цыпленком',
        unit: 'гр',
        weight: 200,
        price: 320,
      },
      {
        name: 'Цезарь с лососем и тигровыми креветками',
        unit: 'гр',
        weight: 200,
        price: 490,
      },
      {
        name: 'Салат Греческий',
        unit: 'гр',
        weight: 200,
        price: 290,
      },
      {
        name: 'Салат с копченым цыпленком, авокадо и виноградом',
        unit: 'гр',
        weight: 200,
        price: 350,
      },
      {
        name: 'Сельдь под шубой',
        unit: 'гр',
        weight: 200,
        price: 260,
      },
      {
        name: 'Салат «Оливье» с языком',
        unit: 'гр',
        weight: 200,
        price: 290,
      },
      {
        name: 'Салат с языком по-русски',
        unit: 'гр',
        weight: 200,
        price: 330,
      },
      {
        name: 'Теплый салат с куриным филе и беконом',
        unit: 'гр',
        weight: 200,
        price: 350,
      },
      {
        name: 'Салат из тигровых креветок со свежим огурцом, томатами и авокадо',
        unit: 'гр',
        weight: 200,
        price: 490,
      },
      {
        name: 'Салат «Лукоморье»',
        unit: 'гр',
        weight: 200,
        price: 520,
      },
      {
        name: 'Салат из кальмаров по-домашнему',
        unit: 'гр',
        weight: 200,
        price: 290,
      },
    ],
  },
  {
    id: 'hot-apetizers',
    image:'img/hot.jpg',
    groupName: 'Горячие закуски',
    dishes: [
      {
        name: 'Жульен мясной',
        unit: 'гр',
        weight: 140,
        price: 190,
      },
      {
        name: 'Жульен с цыпленком',
        unit: 'гр',
        weight: 140,
        price: 190,
      },
      {
        name: 'Жульен из грибов',
        unit: 'гр',
        weight: 140,
        price: 190,
      },
      {
        name: 'Жареные куриные крылышки с острым соусом',
        unit: 'гр',
        weight: 200,
        price: 210,
      },
      {
        name: 'Тигровые креветки с соусом из свежих трав',
        unit: 'гр',
        weight: 180,
        price: 510,
      },
      {
        name: 'Гренки чесночные',
        unit: 'гр',
        weight: 100,
        price: 150,
      },
      {
        name: 'Острые свиные ребрышки',
        unit: 'гр',
        weight: 250,
        price: 350,
      },
      {
        name: 'Кольца кальмара',
        unit: 'гр',
        weight: '150/50',
        price: 340,
      },
      {
        name: 'Луковые кольца',
        unit: 'гр',
        weight: 100,
        price: 180,
      },
      {
        name: 'Большая тарелка к пиву',
        unit: 'гр',
        weight: 350,
        price: 520,
      },
    ],
  },
  {
    id: 'soups',
    image:'img/soup.jpg',
    groupName: 'Супы',
    dishes: [
      {
        name: 'Солянка мясная со сметаной',
        unit: 'гр',
        weight: '250/50',
        price: 320,
      },
      {
        name: 'Уха из трёх видов рыб',
        unit: 'гр',
        weight: 250,
        price: 350,
      },
      {
        name: 'Суп пюре из лесных грибов с гренками',
        unit: 'гр',
        weight: '250/30',
        price: 310,
      },
      {
        name: 'Суп крем из шпината с гренками',
        unit: 'гр',
        weight: '250/30',
        price: 270,
      },
      {
        name: 'Томатный суп с тигровыми креветками',
        unit: 'гр',
        weight: '250/30',
        price: 340,
      },
      {
        name: 'Суп из свинины с овощами',
        unit: 'гр',
        weight: '250/30',
        price: 270,
      },
      {
        name: 'Бульон с пельменями и сметаной',
        unit: 'гр',
        weight: '250/50',
        price: 270,
      },
    ],
  },
  {
    id: 'bread',
    image:'img/bread.jpg',
    groupName: 'Хлеб',
    dishes: [
      {
        name: 'Булочка белая домашняя',
        unit: 'гр',
        weight: 40,
        price: 30,
      },
      {
        name: 'Булочка черная «Баварская»',
        unit: 'гр',
        weight: 40,
        price: 30,
      },
    ]
  },
  {
    id: 'hot-meat',
    image:'img/hot-meat.jpg',
    groupName: 'Горячие блюда из мяса и птицы',
    dishes: [
      {
        name: 'Жареный телячий язык с картофельными драниками и соусом хрен',
        unit: 'гр',
        weight: 300,
        price: 450,
      },
      {
        name: 'Жаркое из двух видов мяса с картофелем и грибами',
        unit: 'гр',
        weight: 350,
        price: 500,
      },
      {
        name: 'Свиная корейка с разварным картофелем',
        unit: 'гр',
        weight: 280,
        price: 380,
      },
      {
        name: 'Свиная вырезка, фаршированная белыми грибами с рисом и сыром пармезан',
        unit: 'гр',
        weight: 300,
        price: 450,
      },
      {
        name: 'Медальоны из телятины с картофельным пюре и овощным рататуем',
        unit: 'гр',
        weight: 300,
        price: 680,
      },
      {
        name: 'Пожарские котлетки с картофелем, запеченным в беконе',
        unit: 'гр',
        weight: 300,
        price: 380,
      },
      {
        name: 'Стейк из свиной шеи с острым соусом',
        unit: 'гр',
        weight: 250,
        price: 390,
      },
      {
        name: 'Куриное филе в апельсиновой глазури с брокколи',
        unit: 'гр',
        weight: 250,
        price: 330,
      },
      {
        name: 'Медальоны из свиной вырезки с овощным миксом',
        unit: 'гр',
        weight: 250,
        price: 550,
      },
      {
        name: 'Цыпленок по-домашнему с разносолами',
        unit: 'гр',
        weight: '500/125/50',
        price: 500,
      },
      {
        name: 'Свиная рулька с домашними разносолами',
        unit: 'гр',
        weight: 1100,
        price: 1100,
      },
      {
        name: 'Пельмени со сметаной',
        unit: 'гр',
        weight: 250,
        price: 390,
      },
      {
        name: 'Шашлык из курицы',
        unit: 'гр',
        weight: '200/50',
        price: 320,
      },
      {
        name: 'Шашлык из свинины',
        unit: 'гр',
        weight: '200/50',
        price: 360,
      },
    ],
  },
  {
    id: 'hot-fish',
    image:'img/hot-fish.jpg',
    groupName: 'Горячие рыбные блюда',
    dishes: [
      {
        name: 'Филе семги с овощным миксом и голландским соусом',
        unit: 'гр',
        weight: 300,
        price: 570,
      },
      {
        name: 'Лосось в кунжуте с картофелем по-деревенски',
        unit: 'гр',
        weight: 250,
        price: 550,
      },
      {
        name: 'Филе лосося запечённое со сливочным сыром в слоеном тесте и с соусом «Тар-тар»',
        unit: 'гр',
        weight: 340,
        price: 550,
      },
      {
        name: 'Дорадо, запечённая с сыром и томатами',
        unit: 'гр',
        weight: 400,
        price: 740,
      },
      {
        name: 'Рагу из кальмаров с овощами в устричном соусе',
        unit: 'гр',
        weight: 330,
        price: 370,
      },
      {
        name: 'Форель жареная на гриле с овощами',
        unit: 'гр',
        weight: 300,
        price: 440,
      },
      {
        name: 'Филе лосося в беконе с овощным салатом',
        unit: 'гр',
        weight: 300,
        price: 530,
      },
      {
        name: 'Обжаренное филе судака с рисом и овощами',
        unit: 'гр',
        weight: 300,
        price: 390,
      },
      {
        name: 'Стейк из лосося со свежими овощами',
        unit: 'гр',
        weight: '160/130',
        price: 780,
      },
      {
        name: 'Сибас с соусом из свежих трав',
        unit: 'гр',
        weight: 350,
        price: 790,
      },
    ],
  },
  {
    id: 'pasta',
    image:'img/pasta.jpg',
    groupName: 'Пасты',
    dishes: [
      {
        name: 'Паста «Карбонара»',
        unit: 'гр',
        weight: 300,
        price: 330,
      },
      {
        name: 'Паста с лососем',
        unit: 'гр',
        weight: 300,
        price: 390,
      },
      {
        name: 'Паста с белыми грибами',
        unit: 'гр',
        weight: 300,
        price: 340,
      },
      {
        name: 'Паста с тигровыми креветками',
        unit: 'гр',
        weight: 300,
        price: 620,
      },
      {
        name: 'Паста с телятиной в сливках с устричным соусом',
        unit: 'гр',
        weight: 300,
        price: 460,
      },
    ]
  },
  {
    id: 'pizza',
    image:'img/pizza.jpg',
    groupName: 'Пицца',
    dishes: [
      {
        name: 'Маргарита',
        unit: 'гр',
        weight: 150,
        price: 290,
      },
      {
        name: 'Баварская',
        unit: 'гр',
        weight: 150,
        price: 290,
      },
      {
        name: 'Сырная',
        unit: 'гр',
        weight: 150,
        price: 290,
      },
      {
        name: 'С копченой грудкой и грибами',
        unit: 'гр',
        weight: 150,
        price: 290,
      },
      {
        subTitle: 'Кесадилья',
      },
      {
        name: 'С сыром',
        unit: 'гр',
        weight: 150,
        price: 250,
      },
      {
        name: 'С мясом',
        unit: 'гр',
        weight: 150,
        price: 250,
      },
      {
        name: 'С цыпленком',
        unit: 'гр',
        weight: 150,
        price: 250,
      },
      {
        name: 'С грибами',
        unit: 'гр',
        weight: 150,
        price: 250,
      },
    ],
  },
  {
    id: 'garnish',
    image:'img/garnish.jpg',
    groupName: 'Гарниры',
    dishes: [
      {
        name: 'Картофель разварной',
        unit: 'гр',
        weight: 150,
        price: 80,
      },
      {
        name: 'Картофель фри',
        unit: 'гр',
        weight: 150,
        price: 140,
      },
      {
        name: 'Картофель по-деревенски',
        unit: 'гр',
        weight: 150,
        price: 150,
      },
      {
        name: 'Драники из картофеля',
        unit: 'гр',
        weight: 150,
        price: 150,
      },
      {
        name: 'Картофель жареный с грибами',
        unit: 'гр',
        weight: 150,
        price: 190,
      },
      {
        name: 'Овощи гриль',
        unit: 'гр',
        weight: 150,
        price: 250,
      },
      {
        name: 'Фасоль стручковая с томатами',
        unit: 'гр',
        weight: 150,
        price: 130,
      },
      {
        name: 'Капуста цветная, брокколи',
        unit: 'гр',
        weight: 150,
        price: 130,
      },
      {
        name: 'Рис припущенный',
        unit: 'гр',
        weight: 150,
        price: 80,
      },
      {
        name: 'Греча с грибами',
        unit: 'гр',
        weight: 200,
        price: 190,
      },
    ],
  },
  {
    id: 'souses',
    image:'img/souse.jpg',
    groupName: 'Соусы',
    dishes: [
      {
        name: 'Голландский',
        unit: 'гр',
        weight: 50,
        price: 50,
      },
      {
        name: 'Соус из свежих трав',
        unit: 'гр',
        weight: 50,
        price: 50,
      },
      {
        name: 'Томатный острый',
        unit: 'гр',
        weight: 50,
        price: 40,
      },
      {
        name: 'Хрен сливочный',
        unit: 'гр',
        weight: 50,
        price: 60,
      },
      {
        name: 'Горчица',
        unit: 'гр',
        weight: 50,
        price: 40,
      },
      {
        name: 'Сметанный с чесноком и зеленью',
        unit: 'гр',
        weight: 50,
        price: 40,
      },
      {
        name: 'Медово-горчичный',
        unit: 'гр',
        weight: 50,
        price: 60,
      },
      {
        name: 'Гранатовый',
        unit: 'гр',
        weight: 50,
        price: 60,
      },
      {
        name: 'Майонез',
        unit: 'гр',
        weight: 50,
        price: 30,
      },
      {
        name: 'Кетчуп',
        unit: 'гр',
        weight: 50,
        price: 40,
      },
      {
        name: 'Кисло-сладкий',
        unit: 'гр',
        weight: 50,
        price: 50,
      },
    ],
  },
  {
    id:'desserts',
    image:'img/desserts.jpg',
    groupName: 'Десерты',
    dishes: [
      {
        name: 'Блинчики',
        unit: 'гр',
        weight: 150,
        price: 120,
        description:'c медом, c вареньем, cо cметаной, cо сгущеным молоком',
      },
      {
        name: 'Жареные бананы с мороженым и шоколадом',
        unit: 'гр',
        weight: 200,
        price: 170,
      },
      {
        name: 'Торт Фантазия',
        unit: 'гр',
        weight: 150,
        price: 190,
      },
      {
        name: 'Фруктовая тарелка',
        unit: 'гр',
        weight: 500,
        price: 350,
      },
      {
        name: 'Малиновый тар-тар',
        unit: 'гр',
        weight: 200,
        price: 290,
      },
      {
        name: 'Штрудель яблочный с ванильным соусом и мороженым',
        unit: 'гр',
        weight: 200,
        price: 220,
      },
      {
        name: 'Мороженое в ассортименте',
        unit: 'гр',
        weight: 50,
        price: 65,
      },
    ],
  },
  {
    id: 'drinks',
    image:'img/drinks.jpg',
    groupName: 'Напитки',
    dishes: [
      {
        subTitle: 'Безалкогольные напитки',
      },
      {
        name: 'Бон аква',
        unit: 'мл',
        weight: 500,
        price: 69,
        description:'газированная, негазированная',
      },
      {
        name: 'Кока кола, Спрайт, Фанта ',
        unit: 'мл',
        weight: 500,
        price: 79,
      },
      {
        name: 'Морс',
        unit: 'мл',
        weight: 250,
        price: 49,
      },
      {
        name: 'Морс',
        unit: 'мл',
        weight: 1000,
        price: 189,
      },
      {
        name: 'Сок пакетированный',
        unit: 'мл',
        weight: 250,
        price: 50,
        description:'апельсин, яблоко, персик, вишня, ананас, томат, красный виноград',
      },
      {
        subTitle: 'Кофе',
      },
      {
        name: 'Эспрессо',
        unit: 'мл',
        weight: 60,
        price: 80,
      },
      {
        name: 'Американо',
        unit: 'мл',
        weight: 220,
        price: 90,
      },
      {
        name: 'Капучино',
        unit: 'мл',
        weight: 220,
        price: 110,
      },
      {
        name: 'Латте',
        unit: 'мл',
        weight: 220,
        price: 140,
      },
      {
        name: 'Мокко',
        unit: 'мл',
        weight: 220,
        price: 160,
      },
      {
        subTitle: 'Безалкогольные коктейли',
      },
      {
        name: 'Молочный коктейль',
        unit: 'мл',
        weight: 280,
        price: 170,
        description:'ванильный, шоколадный, клубничный',
      },
      {
        name: 'Бананово-клубничный смузи',
        unit: 'мл',
        weight: 250,
        price: 140,
      },
      {
        subTitle: 'Чай',
      },
      {
        name: 'Ассам',
        unit: 'мл',
        weight: 400,
        price: 120,
      },
      {
        name: 'Черный с чабрецом',
        unit: 'мл',
        weight: 400,
        price: 120,
      },
      {
        name: 'Эрл грей',
        unit: 'мл',
        weight: 400,
        price: 120,
      },
      {
        name: 'Сенча',
        unit: 'мл',
        weight: 400,
        price: 120,
      },
      {
        name: 'Жасминовый',
        unit: 'мл',
        weight: 400,
        price: 120,
      },
      {
        name: 'Ройбош крем-карамель',
        unit: 'мл',
        weight: 400,
        price: 120,
      },
      {
        name: 'Травяной чай Имбирь-лимон',
        unit: 'мл',
        weight: 400,
        price: 120,
      },
      {
        name: 'Авторский чай в ассортименте',
        unit: 'мл',
        weight: 600,
        price: 190,
      },
    ],
  }
];

export {mainMenu};
